### ISSUE TITLE
Okular as default viewer causes Qt error 

### ISSUE THREAD

**Issue by stefanwezel** [wastedsummer/isnalyser#1]
When Okular is default pdf viewer, *view_graph* causes this error:

``Qt: Session management error: None of the authentication protocols specified are supported``

The resulting graph is still shown, though.

**Comment by alvorithm** [comment]
Have you checked that if this is specific to this pdf, or is it rather due to using `view_graph`?
If it is a bug in `view_graph` I would close it, given that it is not in the critical path for the web-based version of isnalyser.
